/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordProfessionalRouteImport } from './routes/word-professional'
import { Route as VakmensenRouteImport } from './routes/vakmensen'
import { Route as PrijzenRouteImport } from './routes/prijzen'
import { Route as PlaatsOpdrachtRouteImport } from './routes/plaats-opdracht'
import { Route as OpdrachtenRouteImport } from './routes/opdrachten'
import { Route as InloggenRouteImport } from './routes/inloggen'
import { Route as HoeWerktHetRouteImport } from './routes/hoe-werkt-het'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VakmensenIndexRouteImport } from './routes/vakmensen.index'
import { Route as OpdrachtenIndexRouteImport } from './routes/opdrachten.index'
import { Route as VakmensenSlugRouteImport } from './routes/vakmensen.$slug'
import { Route as OpdrachtenSlugRouteImport } from './routes/opdrachten.$slug'
import { Route as CmsSlugRouteImport } from './routes/cms.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardReviewsRouteImport } from './routes/_authenticated/dashboard.reviews'
import { Route as AuthenticatedDashboardProjectenRouteImport } from './routes/_authenticated/dashboard.projecten'
import { Route as AuthenticatedDashboardLeadsRouteImport } from './routes/_authenticated/dashboard.leads'
import { Route as AuthenticatedDashboardInstellingenRouteImport } from './routes/_authenticated/dashboard.instellingen'
import { Route as AuthenticatedDashboardBerichtenRouteImport } from './routes/_authenticated/dashboard.berichten'
import { Route as AuthenticatedDashboardAbonnementRouteImport } from './routes/_authenticated/dashboard.abonnement'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAdminAdminThemaRouteImport } from './routes/_authenticated/_admin/admin.thema'
import { Route as AuthenticatedAdminAdminReviewsRouteImport } from './routes/_authenticated/_admin/admin.reviews'
import { Route as AuthenticatedAdminAdminReviewProfessionalsRouteImport } from './routes/_authenticated/_admin/admin.review-professionals'
import { Route as AuthenticatedAdminAdminReviewOpdrachtenRouteImport } from './routes/_authenticated/_admin/admin.review-opdrachten'
import { Route as AuthenticatedAdminAdminPaginasRouteImport } from './routes/_authenticated/_admin/admin.paginas'
import { Route as AuthenticatedAdminAdminOpdrachtenRouteImport } from './routes/_authenticated/_admin/admin.opdrachten'
import { Route as AuthenticatedAdminAdminGebruikersRouteImport } from './routes/_authenticated/_admin/admin.gebruikers'
import { Route as AuthenticatedAdminAdminCategorieenRouteImport } from './routes/_authenticated/_admin/admin.categorieen'
import { Route as AuthenticatedAdminAdminPaginasSlugRouteImport } from './routes/_authenticated/_admin/admin.paginas.$slug'

const WordProfessionalRoute = WordProfessionalRouteImport.update({
  id: '/word-professional',
  path: '/word-professional',
  getParentRoute: () => rootRouteImport,
} as any)
const VakmensenRoute = VakmensenRouteImport.update({
  id: '/vakmensen',
  path: '/vakmensen',
  getParentRoute: () => rootRouteImport,
} as any)
const PrijzenRoute = PrijzenRouteImport.update({
  id: '/prijzen',
  path: '/prijzen',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaatsOpdrachtRoute = PlaatsOpdrachtRouteImport.update({
  id: '/plaats-opdracht',
  path: '/plaats-opdracht',
  getParentRoute: () => rootRouteImport,
} as any)
const OpdrachtenRoute = OpdrachtenRouteImport.update({
  id: '/opdrachten',
  path: '/opdrachten',
  getParentRoute: () => rootRouteImport,
} as any)
const InloggenRoute = InloggenRouteImport.update({
  id: '/inloggen',
  path: '/inloggen',
  getParentRoute: () => rootRouteImport,
} as any)
const HoeWerktHetRoute = HoeWerktHetRouteImport.update({
  id: '/hoe-werkt-het',
  path: '/hoe-werkt-het',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VakmensenIndexRoute = VakmensenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VakmensenRoute,
} as any)
const OpdrachtenIndexRoute = OpdrachtenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpdrachtenRoute,
} as any)
const VakmensenSlugRoute = VakmensenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VakmensenRoute,
} as any)
const OpdrachtenSlugRoute = OpdrachtenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OpdrachtenRoute,
} as any)
const CmsSlugRoute = CmsSlugRouteImport.update({
  id: '/cms/$slug',
  path: '/cms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReviewsRoute =
  AuthenticatedDashboardReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProjectenRoute =
  AuthenticatedDashboardProjectenRouteImport.update({
    id: '/projecten',
    path: '/projecten',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLeadsRoute =
  AuthenticatedDashboardLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInstellingenRoute =
  AuthenticatedDashboardInstellingenRouteImport.update({
    id: '/instellingen',
    path: '/instellingen',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBerichtenRoute =
  AuthenticatedDashboardBerichtenRouteImport.update({
    id: '/berichten',
    path: '/berichten',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAbonnementRoute =
  AuthenticatedDashboardAbonnementRouteImport.update({
    id: '/abonnement',
    path: '/abonnement',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAdminThemaRoute =
  AuthenticatedAdminAdminThemaRouteImport.update({
    id: '/admin/thema',
    path: '/admin/thema',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminReviewsRoute =
  AuthenticatedAdminAdminReviewsRouteImport.update({
    id: '/admin/reviews',
    path: '/admin/reviews',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminReviewProfessionalsRoute =
  AuthenticatedAdminAdminReviewProfessionalsRouteImport.update({
    id: '/admin/review-professionals',
    path: '/admin/review-professionals',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminReviewOpdrachtenRoute =
  AuthenticatedAdminAdminReviewOpdrachtenRouteImport.update({
    id: '/admin/review-opdrachten',
    path: '/admin/review-opdrachten',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPaginasRoute =
  AuthenticatedAdminAdminPaginasRouteImport.update({
    id: '/admin/paginas',
    path: '/admin/paginas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminOpdrachtenRoute =
  AuthenticatedAdminAdminOpdrachtenRouteImport.update({
    id: '/admin/opdrachten',
    path: '/admin/opdrachten',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminGebruikersRoute =
  AuthenticatedAdminAdminGebruikersRouteImport.update({
    id: '/admin/gebruikers',
    path: '/admin/gebruikers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminCategorieenRoute =
  AuthenticatedAdminAdminCategorieenRouteImport.update({
    id: '/admin/categorieen',
    path: '/admin/categorieen',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPaginasSlugRoute =
  AuthenticatedAdminAdminPaginasSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedAdminAdminPaginasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/hoe-werkt-het': typeof HoeWerktHetRoute
  '/inloggen': typeof InloggenRoute
  '/opdrachten': typeof OpdrachtenRouteWithChildren
  '/plaats-opdracht': typeof PlaatsOpdrachtRoute
  '/prijzen': typeof PrijzenRoute
  '/vakmensen': typeof VakmensenRouteWithChildren
  '/word-professional': typeof WordProfessionalRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/cms/$slug': typeof CmsSlugRoute
  '/opdrachten/$slug': typeof OpdrachtenSlugRoute
  '/vakmensen/$slug': typeof VakmensenSlugRoute
  '/opdrachten/': typeof OpdrachtenIndexRoute
  '/vakmensen/': typeof VakmensenIndexRoute
  '/dashboard/abonnement': typeof AuthenticatedDashboardAbonnementRoute
  '/dashboard/berichten': typeof AuthenticatedDashboardBerichtenRoute
  '/dashboard/instellingen': typeof AuthenticatedDashboardInstellingenRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/projecten': typeof AuthenticatedDashboardProjectenRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/categorieen': typeof AuthenticatedAdminAdminCategorieenRoute
  '/admin/gebruikers': typeof AuthenticatedAdminAdminGebruikersRoute
  '/admin/opdrachten': typeof AuthenticatedAdminAdminOpdrachtenRoute
  '/admin/paginas': typeof AuthenticatedAdminAdminPaginasRouteWithChildren
  '/admin/review-opdrachten': typeof AuthenticatedAdminAdminReviewOpdrachtenRoute
  '/admin/review-professionals': typeof AuthenticatedAdminAdminReviewProfessionalsRoute
  '/admin/reviews': typeof AuthenticatedAdminAdminReviewsRoute
  '/admin/thema': typeof AuthenticatedAdminAdminThemaRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/paginas/$slug': typeof AuthenticatedAdminAdminPaginasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/hoe-werkt-het': typeof HoeWerktHetRoute
  '/inloggen': typeof InloggenRoute
  '/plaats-opdracht': typeof PlaatsOpdrachtRoute
  '/prijzen': typeof PrijzenRoute
  '/word-professional': typeof WordProfessionalRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/cms/$slug': typeof CmsSlugRoute
  '/opdrachten/$slug': typeof OpdrachtenSlugRoute
  '/vakmensen/$slug': typeof VakmensenSlugRoute
  '/opdrachten': typeof OpdrachtenIndexRoute
  '/vakmensen': typeof VakmensenIndexRoute
  '/dashboard/abonnement': typeof AuthenticatedDashboardAbonnementRoute
  '/dashboard/berichten': typeof AuthenticatedDashboardBerichtenRoute
  '/dashboard/instellingen': typeof AuthenticatedDashboardInstellingenRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/projecten': typeof AuthenticatedDashboardProjectenRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/categorieen': typeof AuthenticatedAdminAdminCategorieenRoute
  '/admin/gebruikers': typeof AuthenticatedAdminAdminGebruikersRoute
  '/admin/opdrachten': typeof AuthenticatedAdminAdminOpdrachtenRoute
  '/admin/paginas': typeof AuthenticatedAdminAdminPaginasRouteWithChildren
  '/admin/review-opdrachten': typeof AuthenticatedAdminAdminReviewOpdrachtenRoute
  '/admin/review-professionals': typeof AuthenticatedAdminAdminReviewProfessionalsRoute
  '/admin/reviews': typeof AuthenticatedAdminAdminReviewsRoute
  '/admin/thema': typeof AuthenticatedAdminAdminThemaRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/paginas/$slug': typeof AuthenticatedAdminAdminPaginasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/hoe-werkt-het': typeof HoeWerktHetRoute
  '/inloggen': typeof InloggenRoute
  '/opdrachten': typeof OpdrachtenRouteWithChildren
  '/plaats-opdracht': typeof PlaatsOpdrachtRoute
  '/prijzen': typeof PrijzenRoute
  '/vakmensen': typeof VakmensenRouteWithChildren
  '/word-professional': typeof WordProfessionalRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/cms/$slug': typeof CmsSlugRoute
  '/opdrachten/$slug': typeof OpdrachtenSlugRoute
  '/vakmensen/$slug': typeof VakmensenSlugRoute
  '/opdrachten/': typeof OpdrachtenIndexRoute
  '/vakmensen/': typeof VakmensenIndexRoute
  '/_authenticated/dashboard/abonnement': typeof AuthenticatedDashboardAbonnementRoute
  '/_authenticated/dashboard/berichten': typeof AuthenticatedDashboardBerichtenRoute
  '/_authenticated/dashboard/instellingen': typeof AuthenticatedDashboardInstellingenRoute
  '/_authenticated/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/_authenticated/dashboard/projecten': typeof AuthenticatedDashboardProjectenRoute
  '/_authenticated/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/_admin/admin/categorieen': typeof AuthenticatedAdminAdminCategorieenRoute
  '/_authenticated/_admin/admin/gebruikers': typeof AuthenticatedAdminAdminGebruikersRoute
  '/_authenticated/_admin/admin/opdrachten': typeof AuthenticatedAdminAdminOpdrachtenRoute
  '/_authenticated/_admin/admin/paginas': typeof AuthenticatedAdminAdminPaginasRouteWithChildren
  '/_authenticated/_admin/admin/review-opdrachten': typeof AuthenticatedAdminAdminReviewOpdrachtenRoute
  '/_authenticated/_admin/admin/review-professionals': typeof AuthenticatedAdminAdminReviewProfessionalsRoute
  '/_authenticated/_admin/admin/reviews': typeof AuthenticatedAdminAdminReviewsRoute
  '/_authenticated/_admin/admin/thema': typeof AuthenticatedAdminAdminThemaRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_admin/admin/paginas/$slug': typeof AuthenticatedAdminAdminPaginasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth'
    | '/hoe-werkt-het'
    | '/inloggen'
    | '/opdrachten'
    | '/plaats-opdracht'
    | '/prijzen'
    | '/vakmensen'
    | '/word-professional'
    | '/dashboard'
    | '/checkout/return'
    | '/cms/$slug'
    | '/opdrachten/$slug'
    | '/vakmensen/$slug'
    | '/opdrachten/'
    | '/vakmensen/'
    | '/dashboard/abonnement'
    | '/dashboard/berichten'
    | '/dashboard/instellingen'
    | '/dashboard/leads'
    | '/dashboard/projecten'
    | '/dashboard/reviews'
    | '/dashboard/'
    | '/admin/categorieen'
    | '/admin/gebruikers'
    | '/admin/opdrachten'
    | '/admin/paginas'
    | '/admin/review-opdrachten'
    | '/admin/review-professionals'
    | '/admin/reviews'
    | '/admin/thema'
    | '/api/public/payments/webhook'
    | '/admin/'
    | '/admin/paginas/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/hoe-werkt-het'
    | '/inloggen'
    | '/plaats-opdracht'
    | '/prijzen'
    | '/word-professional'
    | '/checkout/return'
    | '/cms/$slug'
    | '/opdrachten/$slug'
    | '/vakmensen/$slug'
    | '/opdrachten'
    | '/vakmensen'
    | '/dashboard/abonnement'
    | '/dashboard/berichten'
    | '/dashboard/instellingen'
    | '/dashboard/leads'
    | '/dashboard/projecten'
    | '/dashboard/reviews'
    | '/dashboard'
    | '/admin/categorieen'
    | '/admin/gebruikers'
    | '/admin/opdrachten'
    | '/admin/paginas'
    | '/admin/review-opdrachten'
    | '/admin/review-professionals'
    | '/admin/reviews'
    | '/admin/thema'
    | '/api/public/payments/webhook'
    | '/admin'
    | '/admin/paginas/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/auth'
    | '/hoe-werkt-het'
    | '/inloggen'
    | '/opdrachten'
    | '/plaats-opdracht'
    | '/prijzen'
    | '/vakmensen'
    | '/word-professional'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/checkout/return'
    | '/cms/$slug'
    | '/opdrachten/$slug'
    | '/vakmensen/$slug'
    | '/opdrachten/'
    | '/vakmensen/'
    | '/_authenticated/dashboard/abonnement'
    | '/_authenticated/dashboard/berichten'
    | '/_authenticated/dashboard/instellingen'
    | '/_authenticated/dashboard/leads'
    | '/_authenticated/dashboard/projecten'
    | '/_authenticated/dashboard/reviews'
    | '/_authenticated/dashboard/'
    | '/_authenticated/_admin/admin/categorieen'
    | '/_authenticated/_admin/admin/gebruikers'
    | '/_authenticated/_admin/admin/opdrachten'
    | '/_authenticated/_admin/admin/paginas'
    | '/_authenticated/_admin/admin/review-opdrachten'
    | '/_authenticated/_admin/admin/review-professionals'
    | '/_authenticated/_admin/admin/reviews'
    | '/_authenticated/_admin/admin/thema'
    | '/api/public/payments/webhook'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_admin/admin/paginas/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRoute
  HoeWerktHetRoute: typeof HoeWerktHetRoute
  InloggenRoute: typeof InloggenRoute
  OpdrachtenRoute: typeof OpdrachtenRouteWithChildren
  PlaatsOpdrachtRoute: typeof PlaatsOpdrachtRoute
  PrijzenRoute: typeof PrijzenRoute
  VakmensenRoute: typeof VakmensenRouteWithChildren
  WordProfessionalRoute: typeof WordProfessionalRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CmsSlugRoute: typeof CmsSlugRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/word-professional': {
      id: '/word-professional'
      path: '/word-professional'
      fullPath: '/word-professional'
      preLoaderRoute: typeof WordProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vakmensen': {
      id: '/vakmensen'
      path: '/vakmensen'
      fullPath: '/vakmensen'
      preLoaderRoute: typeof VakmensenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prijzen': {
      id: '/prijzen'
      path: '/prijzen'
      fullPath: '/prijzen'
      preLoaderRoute: typeof PrijzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plaats-opdracht': {
      id: '/plaats-opdracht'
      path: '/plaats-opdracht'
      fullPath: '/plaats-opdracht'
      preLoaderRoute: typeof PlaatsOpdrachtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opdrachten': {
      id: '/opdrachten'
      path: '/opdrachten'
      fullPath: '/opdrachten'
      preLoaderRoute: typeof OpdrachtenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inloggen': {
      id: '/inloggen'
      path: '/inloggen'
      fullPath: '/inloggen'
      preLoaderRoute: typeof InloggenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoe-werkt-het': {
      id: '/hoe-werkt-het'
      path: '/hoe-werkt-het'
      fullPath: '/hoe-werkt-het'
      preLoaderRoute: typeof HoeWerktHetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vakmensen/': {
      id: '/vakmensen/'
      path: '/'
      fullPath: '/vakmensen/'
      preLoaderRoute: typeof VakmensenIndexRouteImport
      parentRoute: typeof VakmensenRoute
    }
    '/opdrachten/': {
      id: '/opdrachten/'
      path: '/'
      fullPath: '/opdrachten/'
      preLoaderRoute: typeof OpdrachtenIndexRouteImport
      parentRoute: typeof OpdrachtenRoute
    }
    '/vakmensen/$slug': {
      id: '/vakmensen/$slug'
      path: '/$slug'
      fullPath: '/vakmensen/$slug'
      preLoaderRoute: typeof VakmensenSlugRouteImport
      parentRoute: typeof VakmensenRoute
    }
    '/opdrachten/$slug': {
      id: '/opdrachten/$slug'
      path: '/$slug'
      fullPath: '/opdrachten/$slug'
      preLoaderRoute: typeof OpdrachtenSlugRouteImport
      parentRoute: typeof OpdrachtenRoute
    }
    '/cms/$slug': {
      id: '/cms/$slug'
      path: '/cms/$slug'
      fullPath: '/cms/$slug'
      preLoaderRoute: typeof CmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reviews': {
      id: '/_authenticated/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof AuthenticatedDashboardReviewsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/projecten': {
      id: '/_authenticated/dashboard/projecten'
      path: '/projecten'
      fullPath: '/dashboard/projecten'
      preLoaderRoute: typeof AuthenticatedDashboardProjectenRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/leads': {
      id: '/_authenticated/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof AuthenticatedDashboardLeadsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/instellingen': {
      id: '/_authenticated/dashboard/instellingen'
      path: '/instellingen'
      fullPath: '/dashboard/instellingen'
      preLoaderRoute: typeof AuthenticatedDashboardInstellingenRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/berichten': {
      id: '/_authenticated/dashboard/berichten'
      path: '/berichten'
      fullPath: '/dashboard/berichten'
      preLoaderRoute: typeof AuthenticatedDashboardBerichtenRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/abonnement': {
      id: '/_authenticated/dashboard/abonnement'
      path: '/abonnement'
      fullPath: '/dashboard/abonnement'
      preLoaderRoute: typeof AuthenticatedDashboardAbonnementRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/thema': {
      id: '/_authenticated/_admin/admin/thema'
      path: '/admin/thema'
      fullPath: '/admin/thema'
      preLoaderRoute: typeof AuthenticatedAdminAdminThemaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/reviews': {
      id: '/_authenticated/_admin/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/review-professionals': {
      id: '/_authenticated/_admin/admin/review-professionals'
      path: '/admin/review-professionals'
      fullPath: '/admin/review-professionals'
      preLoaderRoute: typeof AuthenticatedAdminAdminReviewProfessionalsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/review-opdrachten': {
      id: '/_authenticated/_admin/admin/review-opdrachten'
      path: '/admin/review-opdrachten'
      fullPath: '/admin/review-opdrachten'
      preLoaderRoute: typeof AuthenticatedAdminAdminReviewOpdrachtenRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/paginas': {
      id: '/_authenticated/_admin/admin/paginas'
      path: '/admin/paginas'
      fullPath: '/admin/paginas'
      preLoaderRoute: typeof AuthenticatedAdminAdminPaginasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/opdrachten': {
      id: '/_authenticated/_admin/admin/opdrachten'
      path: '/admin/opdrachten'
      fullPath: '/admin/opdrachten'
      preLoaderRoute: typeof AuthenticatedAdminAdminOpdrachtenRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/gebruikers': {
      id: '/_authenticated/_admin/admin/gebruikers'
      path: '/admin/gebruikers'
      fullPath: '/admin/gebruikers'
      preLoaderRoute: typeof AuthenticatedAdminAdminGebruikersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/categorieen': {
      id: '/_authenticated/_admin/admin/categorieen'
      path: '/admin/categorieen'
      fullPath: '/admin/categorieen'
      preLoaderRoute: typeof AuthenticatedAdminAdminCategorieenRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/paginas/$slug': {
      id: '/_authenticated/_admin/admin/paginas/$slug'
      path: '/$slug'
      fullPath: '/admin/paginas/$slug'
      preLoaderRoute: typeof AuthenticatedAdminAdminPaginasSlugRouteImport
      parentRoute: typeof AuthenticatedAdminAdminPaginasRoute
    }
  }
}

interface AuthenticatedAdminAdminPaginasRouteChildren {
  AuthenticatedAdminAdminPaginasSlugRoute: typeof AuthenticatedAdminAdminPaginasSlugRoute
}

const AuthenticatedAdminAdminPaginasRouteChildren: AuthenticatedAdminAdminPaginasRouteChildren =
  {
    AuthenticatedAdminAdminPaginasSlugRoute:
      AuthenticatedAdminAdminPaginasSlugRoute,
  }

const AuthenticatedAdminAdminPaginasRouteWithChildren =
  AuthenticatedAdminAdminPaginasRoute._addFileChildren(
    AuthenticatedAdminAdminPaginasRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminCategorieenRoute: typeof AuthenticatedAdminAdminCategorieenRoute
  AuthenticatedAdminAdminGebruikersRoute: typeof AuthenticatedAdminAdminGebruikersRoute
  AuthenticatedAdminAdminOpdrachtenRoute: typeof AuthenticatedAdminAdminOpdrachtenRoute
  AuthenticatedAdminAdminPaginasRoute: typeof AuthenticatedAdminAdminPaginasRouteWithChildren
  AuthenticatedAdminAdminReviewOpdrachtenRoute: typeof AuthenticatedAdminAdminReviewOpdrachtenRoute
  AuthenticatedAdminAdminReviewProfessionalsRoute: typeof AuthenticatedAdminAdminReviewProfessionalsRoute
  AuthenticatedAdminAdminReviewsRoute: typeof AuthenticatedAdminAdminReviewsRoute
  AuthenticatedAdminAdminThemaRoute: typeof AuthenticatedAdminAdminThemaRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminCategorieenRoute:
      AuthenticatedAdminAdminCategorieenRoute,
    AuthenticatedAdminAdminGebruikersRoute:
      AuthenticatedAdminAdminGebruikersRoute,
    AuthenticatedAdminAdminOpdrachtenRoute:
      AuthenticatedAdminAdminOpdrachtenRoute,
    AuthenticatedAdminAdminPaginasRoute:
      AuthenticatedAdminAdminPaginasRouteWithChildren,
    AuthenticatedAdminAdminReviewOpdrachtenRoute:
      AuthenticatedAdminAdminReviewOpdrachtenRoute,
    AuthenticatedAdminAdminReviewProfessionalsRoute:
      AuthenticatedAdminAdminReviewProfessionalsRoute,
    AuthenticatedAdminAdminReviewsRoute: AuthenticatedAdminAdminReviewsRoute,
    AuthenticatedAdminAdminThemaRoute: AuthenticatedAdminAdminThemaRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAbonnementRoute: typeof AuthenticatedDashboardAbonnementRoute
  AuthenticatedDashboardBerichtenRoute: typeof AuthenticatedDashboardBerichtenRoute
  AuthenticatedDashboardInstellingenRoute: typeof AuthenticatedDashboardInstellingenRoute
  AuthenticatedDashboardLeadsRoute: typeof AuthenticatedDashboardLeadsRoute
  AuthenticatedDashboardProjectenRoute: typeof AuthenticatedDashboardProjectenRoute
  AuthenticatedDashboardReviewsRoute: typeof AuthenticatedDashboardReviewsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAbonnementRoute:
      AuthenticatedDashboardAbonnementRoute,
    AuthenticatedDashboardBerichtenRoute: AuthenticatedDashboardBerichtenRoute,
    AuthenticatedDashboardInstellingenRoute:
      AuthenticatedDashboardInstellingenRoute,
    AuthenticatedDashboardLeadsRoute: AuthenticatedDashboardLeadsRoute,
    AuthenticatedDashboardProjectenRoute: AuthenticatedDashboardProjectenRoute,
    AuthenticatedDashboardReviewsRoute: AuthenticatedDashboardReviewsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface OpdrachtenRouteChildren {
  OpdrachtenSlugRoute: typeof OpdrachtenSlugRoute
  OpdrachtenIndexRoute: typeof OpdrachtenIndexRoute
}

const OpdrachtenRouteChildren: OpdrachtenRouteChildren = {
  OpdrachtenSlugRoute: OpdrachtenSlugRoute,
  OpdrachtenIndexRoute: OpdrachtenIndexRoute,
}

const OpdrachtenRouteWithChildren = OpdrachtenRoute._addFileChildren(
  OpdrachtenRouteChildren,
)

interface VakmensenRouteChildren {
  VakmensenSlugRoute: typeof VakmensenSlugRoute
  VakmensenIndexRoute: typeof VakmensenIndexRoute
}

const VakmensenRouteChildren: VakmensenRouteChildren = {
  VakmensenSlugRoute: VakmensenSlugRoute,
  VakmensenIndexRoute: VakmensenIndexRoute,
}

const VakmensenRouteWithChildren = VakmensenRoute._addFileChildren(
  VakmensenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRoute,
  HoeWerktHetRoute: HoeWerktHetRoute,
  InloggenRoute: InloggenRoute,
  OpdrachtenRoute: OpdrachtenRouteWithChildren,
  PlaatsOpdrachtRoute: PlaatsOpdrachtRoute,
  PrijzenRoute: PrijzenRoute,
  VakmensenRoute: VakmensenRouteWithChildren,
  WordProfessionalRoute: WordProfessionalRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CmsSlugRoute: CmsSlugRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
